#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python manage.py makemigrations
python manage.py makemigrations users finance
python manage.py migrate
echo "Running Production Server..."
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
