# Generated by Django 4.2.4 on 2023-08-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_user_last_name_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Username of User"
            ),
        ),
    ]
