# Generated by Django 4.2.4 on 2023-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", unique=True, verbose_name="Phone Number"),
        ),
    ]
