# Generated by Django 4.2.4 on 2023-09-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.TextField(blank=True, null=True, verbose_name="Location Detail"),
        ),
    ]
