#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py makemigrations users finance
python manage.py migrate
echo "Running server..."
exec python manage.py runserver_plus 0.0.0.0:8000